bubun.url: ${BUBUN_URL}

gocardless:
  api-url: ${GOCARDLESS_API_URL}
  secret-id: ${GOCARDLESS_SECRET_ID}
  secret-key: ${GOCARDLESS_SECRET_KEY}
  resilience.enabled: true

spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    hibernate.ddl-auto: validate
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  threads.virtual.enabled: true
  jackson.default-property-inclusion: NON_NULL

management.endpoint.web.exposure.include: health,info,metrics